import Head from "next/head";

// import { Inter } from "next/font/google";

import "bootstrap/dist/css/bootstrap.css"; 

import Header from "@/components/header.component";
import Footer from "@/components/footer.component";
import ProductCard from "@/components/product-card.component";
import Banner from "@/components/banner.component";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  let products = [1, 2, 3, 4, 5, 6, 7, 8]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <main>
        <Header />
        <Banner />
        <div className="container">
          <div className="row">
            {products.map((product, i) => (<ProductCard key={1}/>))}
          </div>
        </div>
      </main>
    </>
  );
}
