import Head from "next/head";
import Image from "next/image";

import { Inter } from "next/font/google";

import styles from "@/styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.css"; // Add this line

import Header from "@/components/header.component";
import Footer from "@/components/footer.component";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
          crossOrigin="anonymous"
        ></script>
      </Head>
      <main>
        <Header />
        <Footer />
      </main>
    </>
  );
}
